// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "I don't want to use Primary Constructor", Scope = "member", Target = "~M:Rystem.OpenAi.OpenAi.#ctor(Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.OpenAiConfiguration},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.Audio.IOpenAiAudio},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.Audio.IOpenAiSpeech},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.Chat.IOpenAiChat},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.Embedding.IOpenAiEmbedding},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.FineTune.IOpenAiFineTune},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.Files.IOpenAiFile},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.Image.IOpenAiImage},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.Models.IOpenAiModel},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.Moderation.IOpenAiModeration},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.IOpenAiManagement})")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "I don't want to match folder structure", Scope = "namespace", Target = "~N:Rystem.OpenAi")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "I don't want to use Primary Constructor", Scope = "member", Target = "~M:Rystem.OpenAi.OpenAiBuilder`1.#ctor(Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.DefaultServices},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.OpenAiConfiguration},Rystem.OpenAi.OpenAiType[])")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "I don't want to use Primary Constructor", Scope = "member", Target = "~M:Rystem.OpenAi.OpenAiBuilder`3.#ctor(Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.DefaultServices},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.OpenAiConfiguration},Rystem.OpenAi.OpenAiType[])")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Rystem.OpenAi.Audio")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Rystem.OpenAi.Chat")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Rystem.OpenAi.Embedding")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Rystem.OpenAi.Files")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Rystem.OpenAi.Files.OpenAiFile.#ctor(Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.DefaultServices},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.OpenAiConfiguration})")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Rystem.OpenAi.Image")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Rystem.OpenAi.Models.OpenAiModel.#ctor(Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.DefaultServices},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.OpenAiConfiguration})")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Rystem.OpenAi.Moderation")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Microsoft.Extensions.DependencyInjection")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Rystem.OpenAi.OpenAiUtility.#ctor(Rystem.OpenAi.IOpenAiTokenizer)")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Rystem.OpenAi.FineTune")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Rystem.OpenAi.Models")]
[assembly: SuppressMessage("Style", "IDE0130:Namespace does not match folder structure", Justification = "<Pending>", Scope = "namespace", Target = "~N:Rystem.OpenAi.Assistant")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Rystem.OpenAi.Files.OpenAiUploadPartFile.#ctor(Rystem.OpenAi.Files.OpenAiFile,System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Rystem.OpenAi.MimeType.#ctor(System.String)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Rystem.OpenAi.Assistant.OpenAiAssistant.#ctor(Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.DefaultServices},Microsoft.Extensions.DependencyInjection.IFactory{Rystem.OpenAi.OpenAiConfiguration})")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Rystem.OpenAi.Assistant.OpenAiToolResourcesAssistant.#ctor(Rystem.OpenAi.Assistant.OpenAiAssistant)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Rystem.OpenAi.Assistant.OpenAiFileSearchToolResourcesAssistant.#ctor(Rystem.OpenAi.Assistant.OpenAiAssistant,Rystem.OpenAi.Assistant.AssistantFileSearchToolResources)")]
[assembly: SuppressMessage("Style", "IDE0290:Use primary constructor", Justification = "<Pending>", Scope = "member", Target = "~M:Rystem.OpenAi.Assistant.OpenAiFileSearchAssistant.#ctor(Rystem.OpenAi.Assistant.OpenAiAssistant,Rystem.OpenAi.Assistant.AssistantFileSearchTool)")]
