name: PlayFramework.Nuget
on:
  push:
    branches:
      - master
    paths:
      - src/Rystem.PlayFramework/Rystem.PlayFramework.csproj
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    environment: OpenAi.Nuget
    
    steps:
      - name: Delay for 5 minutes
        run: sleep 300

      - name: Publish package
        uses: KeyserDSoze/DefaultAction/pushing_nuget_with_symbols@v1.0.1
        with:
          dotnet-version: ${{ secrets.NET_VERSION }}
          path: src/Rystem.PlayFramework/Rystem.PlayFramework.csproj
          api-key: ${{ secrets.NUGET_API_KEY }}